version: '3.7'

services:
  app:
    build: .
    env_file: .env
    image: elim/habitica-auto-quest-accepter:0.0.2
    restart: on-failure
    # volumes:
    #   - ./accepter.sh:/var/app/accepter.sh
    #   - ./crontab:/var/spool/cron/crontabs/root
